<?php

declare(strict_types=1);

namespace Tests\Unit\Models;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use PHPUnit\Framework\Attributes\CoversClass;
use Tests\TestCase;

/**
 * Unit tests for the Category model.
 *
 * @internal
 */
#[CoversClass(Category::class)]
final class CategoryTest extends TestCase
{
    use RefreshDatabase;
    use WithFaker;

    protected function setUp(): void
    {
        parent::setUp();
        $this->faker = $this->faker();
    }

    protected function tearDown(): void
    {
        \Mockery::close();
        parent::tearDown();
    }

    /**
     * Test that parent relation is a BelongsTo instance.
     */
    public function testParentRelation(): void
    {
        $category = new Category();

        $relation = $category->parent();

        self::assertInstanceOf(BelongsTo::class, $relation);
        self::assertSame(Category::class, $relation->getRelated()::class);
    }

    /**
     * Test that children relation is a HasMany instance.
     */
    public function testChildrenRelation(): void
    {
        $category = new Category();

        $relation = $category->children();

        self::assertInstanceOf(HasMany::class, $relation);
        self::assertSame(Category::class, $relation->getRelated()::class);
    }

    /**
     * Test that products relation is a HasMany instance.
     */
    public function testProductsRelation(): void
    {
        $category = new Category();

        $relation = $category->products();

        self::assertInstanceOf(HasMany::class, $relation);
        self::assertSame(Product::class, $relation->getRelated()::class);
    }

    /**
     * Test scopeActive adds where clause for is_active.
     */
    public function testScopeActive(): void
    {
        $query = Category::query()->active();

        self::assertSame('select * from "categories" where "is_active" = ? and "categories"."deleted_at" is null', $query->toSql());
        self::assertSame([true], $query->getBindings());
    }

    /**
     * Test scopeSearch adds where like clause for name.
     */
    public function testScopeSearch(): void
    {
        $query = Category::query()->search('test');

        self::assertSame('select * from "categories" where "name" like ? and "categories"."deleted_at" is null', $query->toSql());
        self::assertSame(['%test%'], $query->getBindings());
    }

    /**
     * Test that slug and level are auto-generated on creating.
     */
    public function testSlugAndLevelAutoGeneratedOnCreating(): void
    {
        $category = Category::create(['name' => 'Test Category']);

        self::assertNotNull($category->slug);
        self::assertSame('test-category', $category->slug);
        self::assertNotNull($category->level);
        self::assertSame(0, $category->level);
        $category->delete();
    }

    /**
     * Test that level is set based on parent on creating.
     */
    public function testLevelBasedOnParentOnCreating(): void
    {
        $parent = Category::create(['name' => 'Parent', 'level' => 1]);
        $child = Category::create(['name' => 'Child', 'parent_id' => $parent->id]);

        self::assertNotNull($child->level);
        self::assertSame(2, $child->level);
        $child->delete();
        $parent->delete();
    }

    /**
     * Test that slug is updated on name change.
     */
    public function testSlugUpdatedOnNameChange(): void
    {
        $category = Category::create(['name' => 'Old Name']);
        self::assertSame('old-name', $category->slug);

        $category->name = 'New Name';
        $category->save();
        $category->refresh();

        self::assertNotNull($category->slug);
        self::assertSame('new-name', $category->slug);
        $category->delete();
    }

    /**
     * Test that level is updated on parent_id change.
     */
    public function testLevelUpdatedOnParentChange(): void
    {
        $category = Category::create(['name' => 'Category']);
        self::assertSame(0, $category->level);

        $parent = Category::create(['name' => 'Parent', 'level' => 1]);

        $category->parent_id = $parent->id;
        $category->save();
        $category->refresh();

        self::assertNotNull($category->level);
        self::assertSame(2, $category->level);
        $category->delete();
        $parent->delete();
    }

    /**
     * Test getRules returns the validation rules.
     */
    public function testGetRules(): void
    {
        $category = new Category();
        $rules = $category->getRules();

        self::assertIsArray($rules);
        self::assertArrayHasKey('name', $rules);
        self::assertArrayHasKey('slug', $rules);
        self::assertArrayHasKey('level', $rules);
    }
}
