<?php

declare(strict_types=1);

namespace Tests\Unit\Models;

use App\Models\Currency;
use App\Models\PriceOffer;
use App\Models\Product;
use App\Models\Store;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Testing\WithFaker;
use PHPUnit\Framework\Attributes\CoversClass;
use Tests\TestCase;

/**
 * Unit tests for the Store model.
 *
 * @internal
 */
#[CoversClass(Store::class)]
final class StoreTest extends TestCase
{
    use WithFaker;

    protected function setUp(): void
    {
        parent::setUp();
        $this->faker = $this->faker();
    }

    protected function tearDown(): void
    {
        \Mockery::close();
        parent::tearDown();
    }

    /**
     * Test that priceOffers relation is a HasMany instance.
     */
    public function testPriceOffersRelation(): void
    {
        $store = new Store();

        $relation = $store->priceOffers();

        self::assertInstanceOf(HasMany::class, $relation);
        self::assertSame(PriceOffer::class, $relation->getRelated()::class);
    }

    /**
     * Test that products relation is a HasMany instance.
     */
    public function testProductsRelation(): void
    {
        $store = new Store();

        $relation = $store->products();

        self::assertInstanceOf(HasMany::class, $relation);
        self::assertSame(Product::class, $relation->getRelated()::class);
    }

    /**
     * Test that currency relation is a BelongsTo instance.
     */
    public function testCurrencyRelation(): void
    {
        $store = new Store();

        $relation = $store->currency();

        self::assertInstanceOf(BelongsTo::class, $relation);
        self::assertSame(Currency::class, $relation->getRelated()::class);
    }

    /**
     * Test scopeActive adds where clause for is_active.
     */
    public function testScopeActive(): void
    {
        $query = \Mockery::mock(Builder::class);
        $query->shouldReceive('where')->once()->with('is_active', true)->andReturnSelf();

        $store = new Store();
        $result = $store->scopeActive($query);

        self::assertInstanceOf(Builder::class, $result);
    }

    /**
     * Test scopeSearch adds where like clause for name.
     */
    public function testScopeSearch(): void
    {
        $search = 'test';
        $query = \Mockery::mock(Builder::class);
        $query->shouldReceive('where')->once()->with('name', 'like', "%{$search}%")->andReturnSelf();

        $store = new Store();
        $result = $store->scopeSearch($query, $search);

        self::assertInstanceOf(Builder::class, $result);
    }

    /**
     * Test that slug is auto-generated on creating.
     */
    public function testSlugAutoGeneratedOnCreating(): void
    {
        // Create store without slug to ensure it's generated from name
        $store = Store::create(['name' => 'Test Store']);

        self::assertSame('test-store', $store->slug);
        $store->delete();
    }

    /**
     * Test that slug is updated on name change.
     */
    public function testSlugUpdatedOnNameChange(): void
    {
        // Create store without factory to avoid random slug generation
        $store = Store::create(['name' => 'Old Name']);

        $store->name = 'New Name';
        $store->save();

        self::assertSame('new-name', $store->slug);
        $store->delete();
    }

    /**
     * Test generateAffiliateUrl returns productUrl if no affiliate data.
     */
    public function testGenerateAffiliateUrlNoAffiliateData(): void
    {
        $store = new Store();
        $productUrl = 'https://example.com/product';

        $result = $store->generateAffiliateUrl($productUrl);

        // When both affiliate_base_url and affiliate_code are null/empty, return original URL
        self::assertSame('https://example.com/product', $result);
    }

    /**
     * Test generateAffiliateUrl generates affiliate URL.
     */
    public function testGenerateAffiliateUrl(): void
    {
        $store = new Store([
            'affiliate_base_url' => 'https://affiliate.com/{AFFILIATE_CODE}?url={URL}',
            'affiliate_code' => 'CODE123',
        ]);
        $productUrl = 'https://example.com/product';

        $result = $store->generateAffiliateUrl($productUrl);

        self::assertSame('https://affiliate.com/CODE123?url=https%3A//example.com/product', $result);
    }

    /**
     * Test getRules returns the validation rules.
     */
    public function testGetRules(): void
    {
        $store = new Store();
        $rules = $store->getRules();

        self::assertIsArray($rules);
        self::assertArrayHasKey('name', $rules);
        self::assertArrayHasKey('slug', $rules);
        self::assertArrayHasKey('priority', $rules);
    }
}
